from sqlalchemy.types import DECIMAL
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Integer, String, DateTime, SMALLINT, Text, BIGINT, Float, Double, JSON
from sqlalchemy.dialects.mysql import LONGTEXT
from datetime import datetime

Base = declarative_base()

class NewManga(Base):
    __tablename__ = "tx_mangas"

    id = Column(Integer, primary_key=True, autoincrement="auto")
    idx = Column(String(36))
    mal_id = Column(String(36))
    name = Column(String(255))
    alt_name = Column(String(255))
    slug = Column(String(255))
    thumb = Column(String(255))
    cover = Column(String(255))
    description = Column(Text)
    original = Column(String(255))
    original_id = Column(String(255))
    featured = Column(SMALLINT, default=0)
    type = Column(SMALLINT, default=1)
    ordinal = Column(SMALLINT, default=0)
    published = Column(DateTime, default=datetime.now())
    publish_status = Column(DateTime, default=datetime.now())
    finished = Column(SMALLINT, default=0)
    latest_chapter_published= Column(DateTime, default=datetime.now())
    status = Column(SMALLINT, default=1)
    popularity = Column(Integer)
    rank = Column(Integer)
    score = Column(Double)
    num_scoring_users = Column(Integer)
    num_list_users = Column(Integer)
    num_chapters = Column(Integer)
    num_volumes = Column(Integer)
    total_view = Column(Integer)
    manga_authors = Column(String(255))
    manga_genres = Column(String(255))
    manga_type_id = Column(BIGINT, default=1)
    meta_tag_id = Column(BIGINT)
    search_content = Column(Text)
    created_by = Column(BIGINT, default=1)
    updated_by = Column(BIGINT, default=1)
    deleted_by = Column(BIGINT)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now())
    deleted_at = Column(DateTime)

class NewMangaChapters(Base):
    __tablename__ = "tx_manga_chapters"

    id = Column(Integer, primary_key=True, autoincrement="auto")
    idx = Column(String(36))
    name = Column(String(255))
    alt_name = Column(String(255))
    slug = Column(String(255))
    thumb = Column(String(255))
    description = Column(Text)
    original = Column(String(255))
    original_id = Column(String(255))
    ordinal = Column(DECIMAL(10,2))
    chapter_no = Column(Integer)
    chapter_part = Column(SMALLINT, default=0)
    season = Column(SMALLINT, default=0)
    chapter_code = Column(String(255))
    resources =  Column(JSON)
    resource_storage = Column(String(255))
    resource_total = Column(Integer)
    resource_download = Column(SMALLINT, default=0)
    resource_bucket = Column(String(255))
    type = Column(String(255))
    published = Column(DateTime, default=datetime.now())
    status = Column(SMALLINT, default=1)
    total_view = Column(Integer)
    manga_id = Column(Integer)
    created_by = Column(BIGINT, default=1)
    updated_by = Column(BIGINT, default=1)
    deleted_by = Column(BIGINT)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now())
    deleted_at = Column(DateTime)